"""Morning watchlist builder for the SMC paper-trading bot.

Screens the S&P 500 for tickers whose PRIOR close is above their SMA200
-- this IS the backtest's daily_trend_filter: it uses only prior-day
data, so it cannot change intraday, and computing it once each morning
is exactly equivalent to the backtest's per-entry-day check. Survivors
are ranked by 20-day average dollar volume (most liquid first -- these
get the best fills and the most reliable 5-min bar data) and capped at
smc_rules.json's universe.max_watchlist_size, then written to
smc_watchlist.txt for cli/smc_cycle.py.

Scheduled once daily at 09:40 ET (see setup_schedule.py's
HT_SMC_Prefilter). Run before the open, "prior close" is simply the
last completed daily bar; run intraday, today's forming bar is dropped
first so the filter stays anchored to prior-day data either way.

Usage:
    python -m trading_bot.cli.smc_prefilter --dry-run
"""

from __future__ import annotations

import argparse
import json
import math
import sys
import traceback
from datetime import datetime, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

import yfinance as yf

from trading_bot import smc_live
from trading_bot.data.sp500_tickers import SP500_TICKERS
from trading_bot.util.notifier import notify

ET = ZoneInfo("America/New_York")
LOGS_DIR = Path("logs")
PREFILTER_ERRORS_LOG = LOGS_DIR / "smc_prefilter_errors.log"

SMA_WINDOW = 200
DOLLAR_VOLUME_WINDOW = 20
DOWNLOAD_PERIOD = "300d"


def ibkr_to_yahoo(ticker: str) -> str:
    return ticker.replace(" ", "-")


def screen(min_price: float, max_watchlist_size: int) -> dict:
    ibkr_tickers = list(SP500_TICKERS)
    yahoo_tickers = [ibkr_to_yahoo(t) for t in ibkr_tickers]
    yahoo_to_ibkr = dict(zip(yahoo_tickers, ibkr_tickers))

    try:
        data = yf.download(
            tickers=" ".join(yahoo_tickers),
            period=DOWNLOAD_PERIOD,
            interval="1d",
            group_by="ticker",
            threads=5,  # keep at 5 -- see morning_prefilter.py's note on
                        # file-descriptor exhaustion under Task Scheduler
            progress=False,
            auto_adjust=True,
        )
    except Exception as e:
        return {"success": False, "error": f"yf.download raised: {type(e).__name__}: {e}"}

    if data is None or data.empty:
        return {"success": False, "error": "yf.download returned an empty dataframe"}

    today = datetime.now(ET).date()
    survivors = []
    not_uptrend = 0
    below_price = 0
    failed = 0

    for yahoo_ticker in yahoo_tickers:
        try:
            bars = data[yahoo_ticker].dropna(subset=["Close"])
            # Anchor to prior-day data: drop today's forming bar if present.
            bars = bars[[d.date() != today for d in bars.index]]
            if len(bars) < SMA_WINDOW + 1:
                failed += 1
                continue

            prior_close = float(bars["Close"].iloc[-1])
            sma200 = float(bars["Close"].iloc[-SMA_WINDOW:].mean())
            recent = bars.iloc[-DOLLAR_VOLUME_WINDOW:]
            dollar_volume = float((recent["Close"] * recent["Volume"]).mean())

            if not (math.isfinite(prior_close) and math.isfinite(sma200) and math.isfinite(dollar_volume)):
                failed += 1
                continue
            if prior_close < min_price:
                below_price += 1
                continue
            if prior_close <= sma200:
                not_uptrend += 1
                continue

            survivors.append(
                {
                    "ticker": yahoo_to_ibkr[yahoo_ticker],
                    "prior_close": prior_close,
                    "sma200": sma200,
                    "dollar_volume": dollar_volume,
                }
            )
        except (KeyError, IndexError, ValueError):
            failed += 1
            continue

    survivors.sort(key=lambda s: s["dollar_volume"], reverse=True)
    survivors_before_cap = len(survivors)
    survivors = survivors[:max_watchlist_size]

    return {
        "success": True,
        "total_screened": len(ibkr_tickers),
        "survivors": survivors,
        "survivors_before_cap": survivors_before_cap,
        "not_uptrend": not_uptrend,
        "below_price": below_price,
        "failed": failed,
    }


def write_watchlist(survivors: list[dict], total_screened: int, survivors_before_cap: int) -> None:
    now_str = datetime.now(ET).strftime("%Y-%m-%d %H:%M %Z")
    lines = [
        f"# Auto-generated by smc_prefilter.py at {now_str}",
        "# Filter: prior close > SMA200 (the SMC daily_trend_filter), ranked by 20d avg dollar volume",
        f"# Survivors: {len(survivors)} of {survivors_before_cap} in uptrend (screened {total_screened})",
        "#",
    ]
    for s in survivors:
        lines.append(
            f"{s['ticker']}  # close ${s['prior_close']:.2f} > sma200 ${s['sma200']:.2f}, "
            f"$vol {s['dollar_volume'] / 1e6:.0f}M/day"
        )
    smc_live.SMC_WATCHLIST_PATH.write_text("\n".join(lines) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    rules = smc_live.load_smc_rules()
    universe_cfg = rules.get("universe", {})
    min_price = universe_cfg.get("min_price_usd", 3.0)
    max_size = universe_cfg.get("max_watchlist_size", 40)

    result = screen(min_price, max_size)
    hhmm_et = datetime.now(ET).strftime("%H:%M")

    if not result.get("success"):
        print(json.dumps(result))
        if not args.dry_run:
            notify(f"SMC Prefilter FAILED {hhmm_et} ET", result.get("error", "unknown error"), "high")
        sys.exit(1)

    if not args.dry_run:
        write_watchlist(result["survivors"], result["total_screened"], result["survivors_before_cap"])

    summary = {
        "success": True,
        "total_screened": result["total_screened"],
        "survivors_count": len(result["survivors"]),
        "survivors_before_cap": result["survivors_before_cap"],
        "not_uptrend": result["not_uptrend"],
        "below_price": result["below_price"],
        "failed": result["failed"],
        "watchlist_path": None if args.dry_run else str(smc_live.SMC_WATCHLIST_PATH),
    }
    print(json.dumps(summary))

    if not args.dry_run:
        top = ", ".join(s["ticker"] for s in result["survivors"][:10])
        notify(
            f"SMC Prefilter {hhmm_et} ET",
            f"{len(result['survivors'])}/{result['survivors_before_cap']} uptrend tickers "
            f"(of {result['total_screened']})\nTop: {top}",
            "default",
        )


if __name__ == "__main__":
    try:
        main()
    except SystemExit:
        raise
    except Exception as exc:
        LOGS_DIR.mkdir(parents=True, exist_ok=True)
        with PREFILTER_ERRORS_LOG.open("a") as f:
            f.write(f"--- {datetime.now(timezone.utc).isoformat()} ---\n")
            f.write(traceback.format_exc())
            f.write("\n")
        try:
            notify("SMC Prefilter CRASHED", str(exc)[:500], "high")
        except Exception:
            pass
        sys.exit(1)
